function Company() {
	this.table  = "company";
	this.key    = "id";
	this.colums = ["id","company_name","year_est","legal_status","no_of_employees","company_800_number","main_business_ph","contact_email","web_address","main_address","state","zip_code","city","country","business_type","service_area","member_id","created_at","business_description","license_contractor_no","certifications","cellphone","logo","banner"];
	this.id = null;
 	this.company_name = null;
 	this.year_est = null;
 	this.legal_status = null;
 	this.no_of_employees = null;
 	this.company_800_number = null;
 	this.main_business_ph = null;
 	this.contact_email = null;
 	this.web_address = null;
 	this.main_address = null;
 	this.state = null;
 	this.zip_code = null;
 	this.city = null;
 	this.country = null;
 	this.business_type = null;
 	this.service_area = null;
 	this.member_id = null;
 	this.created_at = null;
 	this.business_description = null;
 	this.license_contractor_no = null;
 	this.certifications = null;
 	this.cellphone = null;
 	this.logo = null;
 	this.banner = null;
 	
}
module.exports = Company;