function Sales_rep() {
	this.table  = "sales_rep";
	this.key    = "id";
	this.colums = ["id","first_name","last_name","company_name","year_est","legal_status","no_of_employees","number_800","main_business_ph","contact_email","web_address","main_address","state","zip_code","city","country","service_area","member_id","created_at","is_public","member_sale_id","cellphone","token","is_confirm","job_title"];
	this.id = null;
 	this.first_name = null;
 	this.last_name = null;
 	this.company_name = null;
 	this.year_est = null;
 	this.legal_status = null;
 	this.no_of_employees = null;
 	this.number_800 = null;
 	this.main_business_ph = null;
 	this.contact_email = null;
 	this.web_address = null;
 	this.main_address = null;
 	this.state = null;
 	this.zip_code = null;
 	this.city = null;
 	this.country = null;
 	this.service_area = null;
 	this.member_id = null;
 	this.created_at = null;
 	this.is_public = null;
 	this.member_sale_id = null;
 	this.cellphone = null;
 	this.token = null;
 	this.is_confirm = null;
 	this.job_title = null;
 	
}
module.exports = Sales_rep;